#!/usr/bin/env python3
"""
End-to-end FerrumProxy benchmark harness (cross-platform).

What it does, in order:

  1. Spawns `echo_server.py` on UDP:40000 and TCP:40010 (the "backend").
  2. Runs the baseline bench directly against the echo (kernel + loopback,
     no proxy). This is the number to beat.
  3. Writes a temporary `bench-config.yml` that tells FerrumProxy to relay
     UDP:40001 -> UDP:40000 and TCP:40011 -> TCP:40010, then spawns the
     release `ferrum-proxy` binary.
  4. Runs the proxied bench against 40001 / 40011.
  5. Kills the proxy + echo, prints a summary table with the deltas.

Runs on Windows and Linux with just `python3` and a release build of
`ferrum-proxy`. The proxy binary is auto-located under
`../target/release/ferrum-proxy(.exe)` relative to this script.

Usage:
    python3 run_bench.py --count 1000 --size 512
    python3 run_bench.py --count 1000 --haproxy   # PROXY v2 header on (UDP only)
"""
import argparse
import json
import os
import platform
import shutil
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
BIN = ROOT / "target" / "release" / (
    "ferrum-proxy.exe" if platform.system() == "Windows" else "ferrum-proxy"
)

UDP_ECHO_PORT = 40000
TCP_ECHO_PORT = 40010
UDP_PROXY_PORT = 40001
TCP_PROXY_PORT = 40011

LOG_DIR = HERE / "logs"


def ensure_binary() -> None:
    if not BIN.exists():
        print(f"[bench] release binary not found at {BIN}", file=sys.stderr)
        print("[bench] running: cargo build --release", flush=True)
        subprocess.check_call(["cargo", "build", "--release"], cwd=str(ROOT))
    if not BIN.exists():
        print(f"[bench] cargo build did not produce {BIN}", file=sys.stderr)
        sys.exit(1)


def write_config(path: Path, haproxy: bool) -> None:
    text = f"""# Auto-generated by run_bench.py. Do not edit.
endpoint: 6100
debug: false
firewall:
  enabled: false
ddosGuard:
  enabled: false
highLatency:
  enabled: false
listeners:
  - bind: 0.0.0.0
    udp: {UDP_PROXY_PORT}
    haproxy: {"true" if haproxy else "false"}
    rewriteBedrockPongPorts: false
    targets:
      - host: 127.0.0.1
        udp: {UDP_ECHO_PORT}
  - bind: 0.0.0.0
    tcp: {TCP_PROXY_PORT}
    haproxy: {"true" if haproxy else "false"}
    targets:
      - host: 127.0.0.1
        tcp: {TCP_ECHO_PORT}
"""
    path.write_text(text, encoding="utf-8")


def run_bench_client(protocol: str, port: int, count: int, size: int, label: str) -> dict:
    cmd = [
        sys.executable,
        str(HERE / "bench_client.py"),
        "--protocol", protocol,
        "--host", "127.0.0.1",
        "--port", str(port),
        "--count", str(count),
        "--size", str(size),
        "--label", label,
    ]
    out = subprocess.check_output(cmd, text=True)
    return json.loads(out.strip().splitlines()[-1])


def start_process(argv, out_path: Path):
    out_path.parent.mkdir(parents=True, exist_ok=True)
    logf = open(out_path, "w", encoding="utf-8")
    # Windows: prevent Ctrl+C in this shell from also killing the child
    # before we can send it terminate() cleanly. On POSIX this flag doesn't
    # exist, so we pass 0.
    creationflags = (
        subprocess.CREATE_NEW_PROCESS_GROUP if platform.system() == "Windows" else 0
    )
    proc = subprocess.Popen(
        argv,
        stdout=logf,
        stderr=subprocess.STDOUT,
        creationflags=creationflags,
    )
    return proc, logf


def stop_process(proc: subprocess.Popen, log_file) -> None:
    if proc.poll() is None:
        try:
            proc.terminate()
            proc.wait(timeout=3)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait(timeout=3)
    try:
        log_file.close()
    except OSError:
        pass


def fmt(v):
    return f"{v:>10.4f}" if isinstance(v, (int, float)) else f"{v:>10}"


def print_summary(baseline: dict, proxied: dict) -> None:
    print(f"\n=== {baseline['protocol'].upper()} ({baseline['count']} messages, {baseline['size']} bytes) ===")
    header = f"{'metric':<10}{'baseline':>12}{'proxied':>12}{'delta_ms':>12}{'ratio':>10}"
    print(header)
    print("-" * len(header))
    for field in ["mean_ms", "p50_ms", "p90_ms", "p99_ms", "max_ms", "total_ms"]:
        b = baseline.get(field)
        p = proxied.get(field)
        if b is None or p is None:
            continue
        delta = p - b
        ratio = (p / b) if b > 0 else float("inf")
        print(f"{field:<10}{b:>12.4f}{p:>12.4f}{delta:>+12.4f}{ratio:>10.2f}")
    print(f"loss    : baseline={baseline.get('lost', 0)}/{baseline['count']}  proxied={proxied.get('lost', 0)}/{proxied['count']}")


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--count", type=int, default=1000)
    p.add_argument("--size", type=int, default=512)
    p.add_argument("--haproxy", action="store_true", help="send PROXY v2 header")
    p.add_argument("--skip-tcp", action="store_true")
    p.add_argument("--skip-udp", action="store_true")
    args = p.parse_args()

    ensure_binary()
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    cfg_path = HERE / "bench-config.yml"
    write_config(cfg_path, args.haproxy)

    echo_log = LOG_DIR / "echo.log"
    proxy_log = LOG_DIR / "proxy.log"

    # ---- 1) Start echo server ----
    print("=== 1/4  starting echo server (UDP:40000 + TCP:40010) ===")
    echo_argv = [sys.executable, str(HERE / "echo_server.py")]
    echo_proc, echo_logf = start_process(echo_argv, echo_log)
    time.sleep(0.6)
    if echo_proc.poll() is not None:
        print("[bench] echo server exited immediately; see log:", file=sys.stderr)
        print(echo_log.read_text(encoding="utf-8", errors="replace"))
        return 1

    baseline_results = {}
    proxied_results = {}

    try:
        # ---- 2) Baseline ----
        print("\n=== 2/4  BASELINE bench (direct to echo) ===")
        if not args.skip_udp:
            r = run_bench_client("udp", UDP_ECHO_PORT, args.count, args.size, "baseline")
            print("  UDP: " + json.dumps(r))
            baseline_results["udp"] = r
        if not args.skip_tcp:
            r = run_bench_client("tcp", TCP_ECHO_PORT, args.count, args.size, "baseline")
            print("  TCP: " + json.dumps(r))
            baseline_results["tcp"] = r

        # ---- 3) Start proxy ----
        print(f"\n=== 3/4  starting FerrumProxy (haproxy={args.haproxy}) ===")
        proxy_argv = [str(BIN), "--config", str(cfg_path)]
        proxy_proc, proxy_logf = start_process(proxy_argv, proxy_log)
        time.sleep(1.0)
        if proxy_proc.poll() is not None:
            print("[bench] proxy exited immediately; log:", file=sys.stderr)
            print(proxy_log.read_text(encoding="utf-8", errors="replace"))
            return 1

        try:
            # ---- 4) Proxied ----
            print("\n=== 4/4  PROXIED bench (through FerrumProxy) ===")
            if not args.skip_udp:
                r = run_bench_client("udp", UDP_PROXY_PORT, args.count, args.size, "proxied")
                print("  UDP: " + json.dumps(r))
                proxied_results["udp"] = r
            if not args.skip_tcp:
                r = run_bench_client("tcp", TCP_PROXY_PORT, args.count, args.size, "proxied")
                print("  TCP: " + json.dumps(r))
                proxied_results["tcp"] = r
        finally:
            stop_process(proxy_proc, proxy_logf)
    finally:
        stop_process(echo_proc, echo_logf)

    # ---- summary ----
    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)
    for proto in ("udp", "tcp"):
        if proto in baseline_results and proto in proxied_results:
            print_summary(baseline_results[proto], proxied_results[proto])
    return 0


if __name__ == "__main__":
    sys.exit(main())
