import { readdirSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';

function findFiles(dir: string, baseDir: string = dir): string[] {
  const files: string[] = [];
  
  if (!existsSync(dir)) {
    return files;
  }
  
  const items = readdirSync(dir, { withFileTypes: true });
  
  for (const item of items) {
    const fullPath = join(dir, item.name);
    if (item.isDirectory()) {
      files.push(...findFiles(fullPath, baseDir));
    } else {
      const relativePath = fullPath.substring(baseDir.length + 1).replace(/\\/g, '/');
      files.push(relativePath);
    }
  }
  
  return files;
}

try {
  const publicDir = join(process.cwd(), 'public');
  
  if (!existsSync(publicDir)) {
    console.error('Error: public directory does not exist. Run build:frontend first.');
    process.exit(1);
  }
  
  const files = findFiles(publicDir);
  
  if (files.length === 0) {
    console.error('Error: No files found in public directory. Did you run build:frontend first?');
    process.exit(1);
  }
  
  const imports = files.map((file) => {
    return `import "../public/${file}" with { type: "file" };`;
  }).join('\n');
  
  const content = `// Auto-generated file - DO NOT EDIT
// Generated by scripts/generate-embed-files.ts
// Run 'bun run generate:embed' to regenerate

${imports}

// Re-export for potential use
export {};
`;
  
  const outputPath = join(process.cwd(), 'src', 'embed-files.ts');
  writeFileSync(outputPath, content, 'utf-8');
  
  console.log(`✓ Generated embed-files.ts with ${files.length} files:`);
  files.forEach(f => console.log(`  - ${f}`));
} catch (error) {
  console.error('Error generating embed-files.ts:', error);
  process.exit(1);
}
